# Default post title
# 默认文章标题
default_post_title: 没有标题

# Date Format
# 文章时间戳格式
date_format: YYYY/MM/DD

# Comment 
# 填写 disqus_shortname 即可使用 disqus
comments:
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics: 