# Default post title
default_post_title: Halo

#Date Format
date_format: 2018 年 4 月 1 日

# Comment. 
comments:
  # Disqus comment
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics: 
 